"""
This type stub file was generated by pyright.
"""

import functools
import importlib.resources
import inspect
import tempfile
import os
from xml.etree import ElementTree
from .reg import Registry
from .base_generator import BaseGenerator, BaseGeneratorOptions, SetMergedApiNames, SetOutputDirectory, SetOutputFileName, SetTargetApiName
from . import vulkan_object as vo_module
from .vulkan_object import CapabilityAlias, VulkanObject

_DYNAMIC_EXPORTS = ...
__all__ = ['get_vulkan_object', 'CapabilityAlias', *sorted(_DYNAMIC_EXPORTS)]
@functools.lru_cache(maxsize=1)
def get_vulkan_object(alternative_xml: str = ..., video: bool = ...) -> VulkanObject:
    """
    Parses the bundled Vulkan registry (vk.xml) and returns the populated
    VulkanObject.

    This function encapsulates all the setup logic. The result is cached,
    so subsequent calls are instantaneous.

    Args:
        api_name: The API name to parse from the registry, defaults to 'vulkan'.
        alternative_xml: Supply a full path to a different vk.xml (used for testing future extensions)

    Returns:
        An initialized VulkanObject instance providing access to the
        Vulkan API registry data.
    """
    class _InternalGenerator(BaseGenerator):
        ...
    
    

