"""
This type stub file was generated by pyright.
"""

from .generator import GeneratorOptions, OutputGenerator

class CGeneratorOptions(GeneratorOptions):
    """CGeneratorOptions - subclass of GeneratorOptions.

    Adds options used by COutputGenerator objects during C language header
    generation."""
    def __init__(self, prefixText=..., genFuncPointers=..., protectFile=..., protectFeature=..., protectProto=..., protectProtoStr=..., protectExtensionProto=..., protectExtensionProtoStr=..., protectExportName=..., protectExportProtoStr=..., apicall=..., apientry=..., apientryp=..., indentFuncProto=..., indentFuncPointer=..., alignFuncParam=..., genEnumBeginEndRange=..., genAliasMacro=..., genStructExtendsComment=..., aliasMacro=..., misracstyle=..., misracppstyle=..., **kwargs) -> None:
        """Constructor.
        Additional parameters beyond parent class:

        - prefixText - list of strings to prefix generated header with
        (usually a copyright statement + calling convention macros)
        - protectFile - True if multiple inclusion protection should be
        generated (based on the filename) around the entire header
        - protectFeature - True if #ifndef..#endif protection should be
        generated around a feature interface in the header file
        - genFuncPointers - True if function pointer typedefs should be
        generated
        - protectProto - If conditional protection should be generated
        around prototype declarations, set to either '#ifdef'
        to require opt-in (#ifdef protectProtoStr) or '#ifndef'
        to require opt-out (#ifndef protectProtoStr). Otherwise
        set to None.
        - protectProtoStr - #ifdef/#ifndef symbol to use around prototype
        declarations, if protectProto is set
        - protectExtensionProto - If conditional protection should be generated
        around extension prototype declarations, set to either '#ifdef'
        to require opt-in (#ifdef protectExtensionProtoStr) or '#ifndef'
        to require opt-out (#ifndef protectExtensionProtoStr). Otherwise
        set to None
        - protectExtensionProtoStr - #ifdef/#ifndef symbol to use around
        extension prototype declarations, if protectExtensionProto is set
        - protectExportName - name used to determine if a command is
        exported matching an entry in the XML 'export' attribute.
        Set to None if no matching should be done.
        - protectExportProtoStr - #ifndef symbol to use around prototypes
        for commands that are not exported.
        Set to None if no protection is wanted.
        - apicall - string to use for the function declaration prefix,
        such as APICALL on Windows
        - apientry - string to use for the calling convention macro,
        in typedefs, such as APIENTRY
        - apientryp - string to use for the calling convention macro
        in function pointer typedefs, such as APIENTRYP
        - indentFuncProto - True if prototype declarations should put each
        parameter on a separate line
        - indentFuncPointer - True if typedefed function pointers should put each
        parameter on a separate line
        - alignFuncParam - if nonzero and parameters are being put on a
        separate line, align parameter names at the specified column
        - genEnumBeginEndRange - True if BEGIN_RANGE / END_RANGE macros should
        be generated for enumerated types
        - genAliasMacro - True if the OpenXR alias macro should be generated
        for aliased types (unclear what other circumstances this is useful)
        - genStructExtendsComment - True if comments showing the structures
        whose pNext chain a structure extends are included before its
        definition
        - aliasMacro - alias macro to inject when genAliasMacro is True
        - misracstyle - generate MISRA C-friendly headers
        - misracppstyle - generate MISRA C++-friendly headers"""
        ...
    


class COutputGenerator(OutputGenerator):
    """Generates C-language API interfaces."""
    TYPE_SECTIONS = ...
    ALL_SECTIONS = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def beginFile(self, genOpts) -> None:
        ...
    
    def endFile(self) -> None:
        ...
    
    def beginFeature(self, interface, emit) -> None:
        ...
    
    def endFeature(self) -> None:
        "Actually write the interface to the output file."
        ...
    
    def appendSection(self, section, text) -> None:
        "Append a definition to the specified section"
        ...
    
    def genType(self, typeinfo, name, alias) -> None:
        "Generate type."
        ...
    
    def genProtectString(self, protect_str) -> tuple[Literal[''], Literal['']] | tuple[str, str]:
        """Generate protection string.

        Protection strings are the strings defining the OS/Platform/Graphics
        requirements for a given API command.  When generating the
        language header files, we need to make sure the items specific to a
        graphics API or OS platform are properly wrapped in #ifs.

        Supports boolean expressions using the same syntax as 'depends':
        - '+' for AND
        - ',' for OR
        - '()' for grouping

        Examples:
          'VK_A,VK_B' -> '#if defined(VK_A) || defined(VK_B)'
          'VK_A+VK_B' -> '#if defined(VK_A) && defined(VK_B)'
          '(VK_A+VK_B),VK_C' -> '#if (defined(VK_A) && defined(VK_B)) || defined(VK_C)'
        """
        ...
    
    def typeMayAlias(self, typeName) -> bool:
        ...
    
    def genStruct(self, typeinfo, typeName, alias) -> None:
        """Generate struct (e.g. C "struct" type).

        This is a special case of the <type> tag where the contents are
        interpreted as a set of <member> tags instead of freeform C
        C type declarations. The <member> tags are just like <param>
        tags - they are a declaration of a struct or union member.
        Only simple member declarations are supported (no nested
        structs etc.)

        If alias is not None, then this struct aliases another; just
        generate a typedef of that alias."""
        ...
    
    def genGroup(self, groupinfo, groupName, alias=...) -> None:
        """Generate groups (e.g. C "enum" type).

        These are concatenated together with other types.

        If alias is not None, it is the name of another group type
        which aliases this type; just generate that alias."""
        ...
    
    def genEnum(self, enuminfo, name, alias) -> None:
        """Generate the C declaration for a constant (a single <enum> value).

        <enum> tags may specify their values in several ways, but are usually
        just integers."""
        ...
    
    def genCmd(self, cmdinfo, name, alias) -> None:
        "Command generation"
        ...
    
    def misracstyle(self):
        ...
    
    def misracppstyle(self):
        ...
    


