"""
This type stub file was generated by pyright.
"""

from .spec_tools.conventions import ConventionsBase

CATEGORIES_REQUIRING_VALIDATION = ...
SPECIAL_WORDS = ...
EXCEPTION_PATTERN = ...
MAIN_RE = ...
class VulkanConventions(ConventionsBase):
    @property
    def null(self) -> Literal['`NULL`']:
        """Preferred spelling of NULL."""
        ...
    
    def formatVersion(self, name, apivariant, major, minor) -> str:
        """Mark up an API version name as a link in the spec."""
        ...
    
    def formatExtension(self, name) -> str:
        """Mark up an extension name as a link in the spec."""
        ...
    
    @property
    def struct_macro(self) -> Literal['slink:']:
        """Get the appropriate format macro for a structure.

        Primarily affects generated valid usage statements.
        """
        ...
    
    @property
    def constFlagBits(self) -> Literal[False]:
        """Returns True if static const flag bits should be generated, False if an enumerated type should be generated."""
        ...
    
    @property
    def structtype_member_name(self) -> Literal['sType']:
        """Return name of the structure type member"""
        ...
    
    @property
    def nextpointer_member_name(self) -> Literal['pNext']:
        """Return name of the structure pointer chain member"""
        ...
    
    @property
    def valid_pointer_prefix(self) -> Literal['valid']:
        """Return prefix to pointers which must themselves be valid"""
        ...
    
    def is_structure_type_member(self, paramtype, paramname):
        """Determine if member type and name match the structure type member."""
        ...
    
    def is_nextpointer_member(self, paramtype, paramname):
        """Determine if member type and name match the next pointer chain member."""
        ...
    
    def generate_structure_type_from_name(self, structname) -> LiteralString | str:
        """Generate a structure type name, like VK_STRUCTURE_TYPE_CREATE_INSTANCE_INFO"""
        ...
    
    @property
    def warning_comment(self) -> LiteralString:
        """Return warning comment to be placed in header of generated Asciidoctor files"""
        ...
    
    @property
    def file_suffix(self) -> Literal['.adoc']:
        """Return suffix of generated Asciidoctor files"""
        ...
    
    def api_name(self, spectype=...) -> Literal['Vulkan'] | None:
        """Return API or specification name for citations in ref pages.ref
           pages should link to for

           spectype is the spec this refpage is for: 'api' is the Vulkan API
           Specification. Defaults to 'api'. If an unrecognized spectype is
           given, returns None.
        """
        ...
    
    @property
    def api_prefix(self) -> Literal['VK_']:
        """Return API token prefix"""
        ...
    
    @property
    def write_contacts(self) -> Literal[True]:
        """Return whether contact list should be written to extension appendices"""
        ...
    
    @property
    def write_refpage_include(self) -> Literal[True]:
        """Return whether refpage include should be written to extension appendices"""
        ...
    
    @property
    def member_used_for_unique_vuid(self) -> Literal['sType']:
        """Return the member name used in the VUID-...-...-unique ID."""
        ...
    
    def is_externsync_command(self, protoname) -> bool:
        """Returns True if the protoname element is an API command requiring
           external synchronization
        """
        ...
    
    def is_api_name(self, name):
        """Returns True if name is in the reserved API namespace.
        For Vulkan, these are names with a case-insensitive 'vk' prefix, or
        a 'PFN_vk' function pointer type prefix.
        """
        ...
    
    def specURL(self, spectype=...) -> LiteralString:
        """Return public registry URL which ref pages should link to for the
           current all-extensions HTML specification, so xrefs in the
           asciidoc source that are not to ref pages can link into it
           instead. N.b. this may need to change on a per-refpage basis if
           there are multiple documents involved.
        """
        ...
    
    @property
    def xml_api_name(self) -> Literal['vulkan']:
        """Return the name used in the default API XML registry for the default API"""
        ...
    
    @property
    def registry_path(self) -> Literal['xml/vk.xml']:
        """Return relpath to the default API XML registry in this project."""
        ...
    
    @property
    def specification_path(self) -> Literal['{generated}/meta']:
        """Return relpath to the Asciidoctor specification sources in this project."""
        ...
    
    @property
    def special_use_section_anchor(self) -> Literal['extendingvulkan-compatibility-specialuse']:
        """Return asciidoctor anchor name in the API Specification of the
        section describing extension special uses in detail."""
        ...
    
    @property
    def extension_index_prefixes(self) -> list[str]:
        """Return a list of extension prefixes used to group extension refpages."""
        ...
    
    @property
    def unified_flag_refpages(self) -> Literal[False]:
        """Return True if Flags/FlagBits refpages are unified, False if
           they are separate.
        """
        ...
    
    @property
    def spec_reflow_path(self) -> str:
        """Return the path to the spec source folder to reflow"""
        ...
    
    @property
    def spec_no_reflow_dirs(self) -> tuple[Literal['scripts'], Literal['style']]:
        """Return a set of directories not to automatically descend into
           when reflowing spec text
        """
        ...
    
    @property
    def zero(self) -> Literal['`0`']:
        ...
    
    def category_requires_validation(self, category) -> bool:
        """Return True if the given type 'category' always requires validation.

        Overridden because Vulkan does not require "valid" text for basetype
        in the spec right now."""
        ...
    
    @property
    def should_skip_checking_codes(self) -> Literal[True]:
        """Return True if more than the basic validation of return codes should
        be skipped for a command.

        Vulkan mostly relies on the validation layers rather than API
        builtin error checking, so these checks are not appropriate.

        For example, passing in a VkFormat parameter will not potentially
        generate a VK_ERROR_FORMAT_NOT_SUPPORTED code."""
        ...
    
    def extension_file_path(self, name) -> str:
        """Return file path to an extension appendix relative to a directory
           containing all such appendices.
           - name - extension name"""
        ...
    
    def valid_flag_bit(self, bitpos):
        """Return True if bitpos is an allowed numeric bit position for
           an API flag bit.

           Vulkan uses 32 bit Vk*Flags types, and assumes C compilers may
           cause Vk*FlagBits values with bit 31 set to result in a 64 bit
           enumerated type, so disallows such flags."""
        ...
    
    @property
    def extra_refpage_headers(self) -> Literal['include::{config}/attribs.adoc[]']:
        """Return any extra text to add to refpage headers."""
        ...
    
    @property
    def extra_refpage_body(self) -> Literal['include::{generated}/specattribs.adoc[]']:
        """Return any extra text (following the title) for generated
           reference pages."""
        ...
    


class VulkanSCConventions(VulkanConventions):
    def specURL(self, spectype=...) -> LiteralString:
        """Return public registry URL which ref pages should link to for the
           current all-extensions HTML specification, so xrefs in the
           asciidoc source that are not to ref pages can link into it
           instead. N.b. this may need to change on a per-refpage basis if
           there are multiple documents involved.
        """
        ...
    
    @property
    def xml_api_name(self) -> Literal['vulkansc']:
        """Return the name used in the default API XML registry for the default API"""
        ...
    


class VulkanBaseConventions(VulkanConventions):
    def specURL(self, spectype=...) -> LiteralString:
        """Return public registry URL which ref pages should link to for the
           current all-extensions HTML specification, so xrefs in the
           asciidoc source that are not to ref pages can link into it
           instead. N.b. this may need to change on a per-refpage basis if
           there are multiple documents involved.
        """
        ...
    
    @property
    def xml_api_name(self) -> Literal['vulkanbase']:
        """Return the name used in the default API XML registry for the default API"""
        ...
    


