"""
This type stub file was generated by pyright.
"""

"""Base class for source/header/doc generators, as well as some utility functions."""
def write(*args, **kwargs) -> None:
    ...

def noneStr(s) -> Literal['']:
    """Return string argument, or "" if argument is None.

    Used in converting etree Elements into text.
    s - string to convert"""
    ...

def enquote(s) -> str | None:
    """Return string argument with surrounding quotes,
      for serialization into Python code."""
    ...

def genProtectDirective(protect_str) -> tuple[Literal[''], Literal['']] | tuple[str, Literal['#endif']]:
    """Generate protection preprocessor directive.

    Protection strings are the strings defining the OS/Platform/Graphics
    requirements for a given API element. When generating the
    language header files, we need to make sure the items specific to a
    graphics API or OS platform are properly wrapped in #ifs.

    Supports boolean expressions using the same syntax as 'depends':
    - '+' for AND
    - ',' for OR
    - '()' for grouping

    Examples:
      'VK_A,VK_B' -> '#if defined(VK_A) || defined(VK_B)'
      'VK_A+VK_B' -> '#if defined(VK_A) && defined(VK_B)'
      '(VK_A+VK_B),VK_C' -> '#if (defined(VK_A) && defined(VK_B)) || defined(VK_C)'

    - protect_str - string with boolean expression of defines, or single define

    Returns a tuple of (opening_directive, closing_directive) strings."""
    ...

def regSortFeatures(orderedFeatureNames, features) -> None:
    """Default sort procedure for generated features.

    - orderedFeatureNames - list of feature / extension names to sort
    - features - dictionary of FeatureInfo keyed by names

    - Sorts by explicit sort order (default 0) relative to other features
    - then by feature category ('feature' or 'extension'),
    - then by version number (for features)
    - then by extension number (for extensions)"""
    ...

class MissingGeneratorOptionsError(RuntimeError):
    """Error raised when a Generator tries to do something that requires GeneratorOptions but it is None."""
    def __init__(self, msg=...) -> None:
        ...
    


class MissingRegistryError(RuntimeError):
    """Error raised when a Generator tries to do something that requires a Registry object but it is None."""
    def __init__(self, msg=...) -> None:
        ...
    


class MissingGeneratorOptionsConventionsError(RuntimeError):
    """Error raised when a Generator tries to do something that requires a Conventions object but it is None."""
    def __init__(self, msg=...) -> None:
        ...
    


class GeneratorOptions:
    """Base class for options used during header/documentation production.

    These options are target language independent, and used by
    Registry.apiGen() and by base OutputGenerator objects."""
    def __init__(self, conventions=..., filename=..., directory=..., genpath=..., apiname=..., mergeApiNames=..., mergeInternalApis=..., profile=..., versions=..., emitversions=..., defaultExtensions=..., addExtensions=..., removeExtensions=..., emitExtensions=..., emitSpirv=..., emitFormats=..., reparentEnums=..., sortProcedure=..., requireCommandAliases=..., requireDepends=...) -> None:
        """Constructor.

        Arguments:

        - conventions - may be mandatory for some generators:
        an object that implements ConventionsBase
        - filename - basename of file to generate, or None to write to stdout.
        - directory - directory in which to generate filename
        - genpath - path to previously generated files, such as apimap.py
        - apiname - string matching `<api>` 'apiname' attribute, e.g. 'gl'.
        - mergeApiNames - If not None, a comma separated list of API names
          to merge into the API specified by 'apiname'
        - mergeInternalApis - whether to merge internal APIs into public APIs
        - profile - string specifying API profile , e.g. 'core', or None.
        - versions - regex matching API versions to process interfaces for.
        Normally `'.*'` or `'[0-9][.][0-9]'` to match all defined versions.
        - emitversions - regex matching API versions to actually emit
        interfaces for (though all requested versions are considered
        when deciding which interfaces to generate). For GL 4.3 glext.h,
        this might be `'1[.][2-5]|[2-4][.][0-9]'`.
        - defaultExtensions - If not None, a string which must in its
        entirety match the pattern in the "supported" attribute of
        the `<extension>`. Defaults to None. Usually the same as apiname.
        - addExtensions - regex matching names of additional extensions
        to include. Defaults to None.
        - removeExtensions - regex matching names of extensions to
        remove (after defaultExtensions and addExtensions). Defaults
        to None.
        - emitExtensions - regex matching names of extensions to actually emit
        interfaces for (though all requested versions are considered when
        deciding which interfaces to generate). Defaults to None.
        - emitSpirv - regex matching names of extensions and capabilities
        to actually emit interfaces for.
        - emitFormats - regex matching names of formats to actually emit
        interfaces for.
        - reparentEnums - move <enum> elements which extend an enumerated
        type from <feature> or <extension> elements to the target <enums>
        element. This is required for almost all purposes, but the
        InterfaceGenerator relies on the list of interfaces in the <feature>
        or <extension> being complete. Defaults to True.
        - sortProcedure - takes a list of FeatureInfo objects and sorts
        them in place to a preferred order in the generated output.
        - requireCommandAliases - if True, treat command aliases
        as required dependencies.
        - requireDepends - whether to follow API dependencies when emitting
        APIs.

        Default is
          - core API versions
          - Khronos (ARB/KHR/OES) extensions
          - All other extensions
          - By core API version number or extension number in each group.

        The regex patterns can be None or empty, in which case they match
        nothing."""
        ...
    
    def emptyRegex(self, pat) -> Literal['_nomatch_^']:
        """Substitute a regular expression which matches no version
        or extension names for None or the empty string."""
        ...
    


class OutputGenerator:
    """Generate specified API interfaces in a specific style, such as a C header.

    Base class for generating API interfaces.
    Manages basic logic, logging, and output file control.
    Derived classes actually generate formatted output.
    """
    categoryToPath = ...
    def breakName(self, name, msg) -> None:
        """Break into debugger if this is a special name"""
        ...
    
    def __init__(self, errFile=..., warnFile=..., diagFile=...) -> None:
        """Constructor

        - errFile, warnFile, diagFile - file handles to write errors,
          warnings, diagnostics to. May be None to not write."""
        ...
    
    def logMsg(self, level, *args) -> None:
        """Write a message of different categories to different
        destinations.

        - `level`
          - 'diag' (diagnostic, voluminous)
          - 'warn' (warning)
          - 'error' (fatal error - raises exception after logging)

        - `*args` - print()-style arguments to direct to corresponding log"""
        ...
    
    def enumToValue(self, elem, needsNum, bitwidth=..., forceSuffix=..., parent_for_alias_dereference=...) -> list[int | str | Any | None] | list[int | str] | tuple[None, Any] | list[None]:
        """Parse and convert an `<enum>` tag into a value.

        - elem - <enum> Element
        - needsNum - generate a numeric representation of the element value
        - bitwidth - size of the numeric representation in bits (32 or 64)
        - forceSuffix - if True, always use a 'U' / 'ULL' suffix on integers
        - parent_for_alias_dereference - if not None, an Element containing
          the parent of elem, used to look for elements this is an alias of

        Returns a list:

        - first element - integer representation of the value, or None
          if needsNum is False. The value must be a legal number
          if needsNum is True.
        - second element - string representation of the value

        There are several possible representations of values.

        - A 'value' attribute simply contains the value.
        - A 'bitpos' attribute defines a value by specifying the bit
          position which is set in that value.
        - An 'offset','extbase','extends' triplet specifies a value
          as an offset to a base value defined by the specified
          'extbase' extension name, which is then cast to the
          typename specified by 'extends'. This requires probing
          the registry database, and imbeds knowledge of the
          API extension enum scheme in this function.
        - An 'alias' attribute contains the name of another enum
          which this is an alias of. The other enum must be
          declared first when emitting this enum."""
        ...
    
    def checkDuplicateEnums(self, enums) -> list[Any]:
        """Check enumerated values for duplicates.

        -  enums - list of `<enum>` Elements

        returns the list with duplicates stripped"""
        ...
    
    def misracstyle(self) -> Literal[False]:
        ...
    
    def misracppstyle(self) -> Literal[False]:
        ...
    
    def deprecationComment(self, elem, indent=...) -> str:
        """If an API element is marked deprecated, return a brief comment
           describing why.
           Otherwise, return an empty string.

          - elem - Element of the API.
            API name is determined depending on the element tag.
          - indent - number of spaces to indent the comment"""
        ...
    
    def buildEnumCDecl(self, expand, groupinfo, groupName) -> tuple[Literal['bitmask'], str] | tuple[Literal['bitmask', 'group'], LiteralString]:
        """Generate the C declaration for an enum"""
        ...
    
    def buildEnumCDecl_BitmaskOrDefine(self, groupinfo, groupName, bitwidth, usedefine) -> tuple[Literal['bitmask'], str]:
        """Generate the C declaration for an "enum" that is actually a
        set of flag bits"""
        ...
    
    def buildEnumCDecl_Enum(self, expand, groupinfo, groupName) -> tuple[Literal['bitmask', 'group'], LiteralString]:
        """Generate the C declaration for an enumerated type"""
        ...
    
    def buildConstantCDecl(self, enuminfo, name, alias) -> str:
        """Generate the C declaration for a constant (a single <enum>
        value).

        <enum> tags may specify their values in several ways, but are
        usually just integers or floating-point numbers."""
        ...
    
    def makeDir(self, path) -> None:
        """Create a directory, if not already done.

        Generally called from derived generators creating hierarchies."""
        ...
    
    def beginFile(self, genOpts) -> None:
        """Start a new interface file

        - genOpts - GeneratorOptions controlling what is generated and how"""
        ...
    
    def endFile(self) -> None:
        ...
    
    def beginFeature(self, interface, emit) -> None:
        """Write interface for a feature and tag generated features as having been done.

        - interface - element for the `<version>` / `<extension>` to generate
        - emit - actually write to the header only when True"""
        ...
    
    def endFeature(self) -> None:
        """Finish an interface file, closing it when done.

        Derived classes responsible for emitting feature"""
        ...
    
    def genRequirements(self, name, mustBeFound=..., indent=...) -> Literal['']:
        """Generate text showing what core versions and extensions introduce
        an API. This exists in the base Generator class because it is used by
        the shared enumerant-generating interfaces (buildEnumCDecl, etc.).
        Here it returns an empty string for most generators, but can be
        overridden by e.g. DocGenerator.

        - name - name of the API
        - mustBeFound - If True, when requirements for 'name' cannot be
          determined, a warning comment is generated.
        """
        ...
    
    def validateFeature(self, featureType, featureName) -> None:
        """Validate we are generating something only inside a `<feature>` tag"""
        ...
    
    def genType(self, typeinfo, name, alias) -> None:
        """Generate interface for a type

        - typeinfo - TypeInfo for a type

        Extend to generate as desired in your derived class."""
        ...
    
    def genStruct(self, typeinfo, typeName, alias) -> None:
        """Generate interface for a C "struct" type.

        - typeinfo - TypeInfo for a type interpreted as a struct

        Extend to generate as desired in your derived class."""
        ...
    
    def genGroup(self, groupinfo, groupName, alias) -> None:
        """Generate interface for a group of enums (C "enum")

        - groupinfo - GroupInfo for a group.

        Extend to generate as desired in your derived class."""
        ...
    
    def genEnum(self, enuminfo, typeName, alias) -> None:
        """Generate interface for an enum (constant).

        - enuminfo - EnumInfo for an enum
        - name - enum name

        Extend to generate as desired in your derived class."""
        ...
    
    def genCmd(self, cmd, cmdinfo, alias) -> None:
        """Generate interface for a command.

        - cmdinfo - CmdInfo for a command

        Extend to generate as desired in your derived class."""
        ...
    
    def genSpirv(self, spirv, spirvinfo, alias) -> None:
        """Generate interface for a spirv element.

        - spirvinfo - SpirvInfo for a command

        Extend to generate as desired in your derived class."""
        ...
    
    def genFormat(self, format, formatinfo, alias) -> None:
        """Generate interface for a format element.

        - formatinfo - FormatInfo

        Extend to generate as desired in your derived class."""
        ...
    
    def genSyncStage(self, stageinfo) -> None:
        """Generate interface for a sync stage element.

        - stageinfo - SyncStageInfo

        Extend to generate as desired in your derived class."""
        ...
    
    def genSyncAccess(self, accessinfo) -> None:
        """Generate interface for a sync stage element.

        - accessinfo - AccessInfo

        Extend to generate as desired in your derived class."""
        ...
    
    def genSyncPipeline(self, pipelineinfo) -> None:
        """Generate interface for a sync stage element.

        - pipelineinfo - SyncPipelineInfo

        Extend to generate as desired in your derived class."""
        ...
    
    def makeProtoName(self, name, tail):
        """Turn a `<proto>` `<name>` into C-language prototype
        and typedef declarations for that name.

        - name - contents of `<name>` tag
        - tail - whatever text follows that tag in the Element"""
        ...
    
    def makeTypedefName(self, name, tail, isfuncpointer) -> str:
        """Make the function-pointer typedef name for a command or
           funcpointer name.
           If this is a function pointer <type> tag, do not prepend a PFN_
           to the name, as that is actually the type name and already
           included.
        """
        ...
    
    def makeCParamDecl(self, param, aligncol) -> str | LiteralString:
        """Return a string which is an indented, formatted
        declaration for a `<param>` or `<member>` block (e.g. function parameter
        or structure/union member).

        - param - Element (`<param>` or `<member>`) to format
        - aligncol - if non-zero, attempt to align the nested `<name>` element
          at this column"""
        ...
    
    def getCParamTypeLength(self, param) -> int:
        """Return the length of the type field is an indented, formatted
        declaration for a `<param>` or `<member>` block (e.g. function parameter
        or structure/union member).

        - param - Element (`<param>` or `<member>`) to identify"""
        ...
    
    def getMaxCParamTypeLength(self, info) -> int:
        """Return the length of the longest type field for a member/parameter.

        - info - TypeInfo or CommandInfo.
        """
        ...
    
    def getHandleParent(self, typename) -> None:
        """Get the parent of a handle object."""
        ...
    
    def iterateHandleAncestors(self, typename) -> Generator[Any, Any, None]:
        """Iterate through the ancestors of a handle type."""
        ...
    
    def getHandleAncestors(self, typename) -> list[Any]:
        """Get the ancestors of a handle object."""
        ...
    
    def getTypeCategory(self, typename) -> None:
        """Get the category of a type."""
        ...
    
    def isStructAlwaysValid(self, structname) -> bool:
        """Try to do check if a structure is always considered valid (i.e. there is no rules to its acceptance)."""
        ...
    
    def paramIsArray(self, param) -> bool:
        """Check if the parameter passed in is a pointer to an array.

        param           the XML information for the param
        """
        ...
    
    def paramIsPointer(self, param) -> bool:
        """Check if the parameter passed in is a pointer.

        param           the XML information for the param
        """
        ...
    
    def isEnumRequired(self, elem) -> bool:
        """Return True if this `<enum>` element is
        required, False otherwise

        - elem - `<enum>` element to test"""
        ...
    
    def makeCDecls(self, cmd) -> list[str | Any | None] | list[str | Any]:
        """Return C prototype and function pointer typedef for a
        `<command>` or `type category="funcpointer"` Element, as a
        two-element list of strings [prototype, typedef].

        - cmd - Element containing a command or funcpointer tag"""
        ...
    
    def newline(self) -> None:
        """Print a newline to the output file (utility function)"""
        ...
    
    def setRegistry(self, registry) -> None:
        ...
    


