"""
This type stub file was generated by pyright.
"""

conventions = ...
def markupPassthrough(name):
    """Pass a name (leaf or operator) through without applying markup"""
    ...

def leafMarkupAsciidoc(name) -> str:
    """Markup a leaf name as an asciidoc link to an API version or extension
       anchor.

       - name - version or extension name"""
    ...

def leafMarkupC(name) -> str:
    """Markup a leaf name as a C expression, using conventions of the
       Vulkan Validation Layers

       - name - version or extension name"""
    ...

def leafMarkupCProtect(name) -> str:
    """Markup a leaf name as a C preprocessor defined() expression
       for use in protect attributes. Supports '!' prefix for negation.

       - name - preprocessor macro name (optionally prefixed with '!' for NOT)"""
    ...

opMarkupAsciidocMap = ...
def opMarkupAsciidoc(op) -> str:
    """Markup an operator as an asciidoc spec markup equivalent

       - op - operator ('+' or ',')"""
    ...

opMarkupCMap = ...
def opMarkupC(op) -> str:
    """Markup an operator as a C language equivalent

       - op - operator ('+' or ',')"""
    ...

exprStack = ...
def push_first(toks) -> None:
    """Push a token on the global stack

       - toks - first element is the token to push"""
    ...

dependencyIdent = ...
dependencyExpr = ...
_bnf = ...
def dependencyBNF() -> Forward:
    """
    boolop  :: '+' | ','
    extname :: Char(alphas)
    atom    :: extname | '(' expr ')'
    expr    :: atom [ boolop atom ]*
    """
    ...

protectIdent = ...
_protect_bnf = ...
def protectBNF() -> Forward:
    """BNF grammar for protect expressions; same as dependencyBNF but supports '!' unary NOT prefix.

    boolop  :: '+' | ','
    macroname :: '!'? Char(alphanums + '_:')
    atom    :: macroname | '(' expr ')'
    expr    :: atom [ boolop atom ]*
    """
    ...

_opn = ...
def evaluateStack(stack, isSupported):
    """Evaluate an expression stack, returning a boolean result.

     - stack - the stack
     - isSupported - function taking a version or extension name string and
       returning True or False if that name is supported or not."""
    ...

def evaluateDependency(dependency, isSupported):
    """Evaluate a dependency expression, returning a boolean result.

     - dependency - the expression
     - isSupported - function taking a version or extension name string and
       returning True or False if that name is supported or not."""
    ...

def evalDependencyLanguage(stack, leafMarkup, opMarkup, parenthesize, root, parent_op=...) -> str:
    """Evaluate an expression stack, returning an English equivalent

     - stack - the stack
     - leafMarkup, opMarkup, parenthesize - same as dependencyLanguage
     - root - True only if this is the outer (root) expression level
     - parent_op - the parent operator ('+' or ','), used to avoid unnecessary parentheses"""
    ...

def dependencyLanguage(dependency, leafMarkup, opMarkup, parenthesize) -> str:
    """Return an API dependency expression translated to a form suitable for
       asciidoctor conditionals or header file comments.

     - dependency - the expression
     - leafMarkup - function taking an extension / version name and
                    returning an equivalent marked up version
     - opMarkup - function taking an operator ('+' / ',') name name and
                  returning an equivalent marked up version
     - parenthesize - True if parentheses should be used in the resulting
                      expression, False otherwise"""
    ...

def dependencyLanguageComment(dependency) -> str:
    """Return dependency expression translated to a form suitable for
       comments in headers of emitted C code, as used by the
       docgenerator."""
    ...

def dependencyLanguageSpecMacros(dependency) -> str:
    """Return dependency expression translated to a form suitable for
       comments in headers of emitted C code, as used by the
       interfacegenerator."""
    ...

def dependencyLanguageC(dependency) -> str:
    """Return dependency expression translated to a form suitable for
       use in C expressions"""
    ...

def protectLanguageC(protect) -> str:
    """Return protect expression translated to a form suitable for
       use in C preprocessor conditionals (#if expressions).

       This wraps each identifier in defined() and converts operators:
       - '+' becomes '&&' (AND)
       - ',' becomes '||' (OR)
       Supports '!' prefix on identifiers for NOT:
       - '!A' becomes '!defined(A)'

       Examples:
         'VK_A,VK_B' -> 'defined(VK_A) || defined(VK_B)'
         'VK_A+VK_B' -> 'defined(VK_A) && defined(VK_B)'
         '(VK_A+VK_B),VK_C' -> '(defined(VK_A) && defined(VK_B)) || defined(VK_C)'
         'VK_A+!VK_B' -> 'defined(VK_A) && !defined(VK_B)'

       - protect - the protect expression string"""
    ...

def evalDependencyNames(stack) -> set[Any]:
    """Evaluate an expression stack, returning the set of extension and
       feature names used in the expression.

     - stack - the stack"""
    ...

def dependencyNames(dependency) -> set[Any]:
    """Return a set of the extension and version names in an API dependency
       expression. Used when determining transitive dependencies for spec
       generation with specific extensions included.

     - dependency - the expression"""
    ...

def markupTraverse(expr, level=..., root=...) -> str:
    """Recursively process a dependency in infix form, transforming it into
       asciidoctor markup with expression nesting indicated by indentation
       level.

       - expr - expression to process
       - level - indentation level to render expression at
       - root - True only on initial call"""
    ...

def dependencyMarkup(dependency) -> LiteralString | str:
    """Return asciidoctor markup for a human-readable equivalent of an API
       dependency expression, suitable for use in extension appendix
       metadata.

     - dependency - the expression"""
    ...

if __name__ == "__main__":
    termdict = ...
    termSupported = ...
    def test(dependency, expected) -> None:
        ...
    
