"""
This type stub file was generated by pyright.
"""

"""Types and classes for manipulating an API registry."""
def apiNameMatch(str, supported) -> bool:
    """Return whether a required api name matches a pattern specified for an
    XML <feature> 'api' attribute or <extension> 'supported' attribute.

    - str - API name such as 'vulkan' or 'openxr'. May be None, in which
        case it never matches (this should not happen).
    - supported - comma-separated list of XML API names. May be None, in
        which case str always matches (this is the usual case)."""
    ...

def matchAPIProfile(api, profile, elem) -> bool:
    """Return whether an API and profile
    being generated matches an element's profile

    - api - string naming the API to match
    - profile - string naming the profile to match
    - elem - Element which (may) have 'api' and 'profile'
      attributes to match to.

    If a tag is not present in the Element, the corresponding API
      or profile always matches.

    Otherwise, the tag must exactly match the API or profile.

    Thus, if 'profile' = core:

    - `<remove>`  with no attribute will match
    - `<remove profile="core">` will match
    - `<remove profile="compatibility">` will not match

    Possible match conditions:

    ```
      Requested   Element
      Profile     Profile
      ---------   --------
      None        None        Always matches
      'string'    None        Always matches
      None        'string'    Does not match. Cannot generate multiple APIs
                              or profiles, so if an API/profile constraint
                              is present, it must be asked for explicitly.
      'string'    'string'    Strings must match
    ```

    ** In the future, we will allow regexes for the attributes,
    not just strings, so that `api="^(gl|gles2)"` will match. Even
    this is not really quite enough, we might prefer something
    like `"gl(core)|gles1(common-lite)"`."""
    ...

def mergeAPIs(tree, fromApiNames, toApiName) -> None:
    """Merge multiple APIs using the precedence order specified in apiNames.
    Also deletes <remove> elements.

        tree - Element at the root of the hierarchy to merge.
        apiNames - list of strings of API names."""
    ...

def mergeInternalFeatures(tree, apiName) -> None:
    """Merge internal API features (apitype='internal') into their public dependents.

    This processes the tree to find features marked with apitype='internal' and merges
    their <require>, <deprecate>, and <remove> blocks into the first public feature
    that depends on them. After merging, the internal features are removed from the tree.

        tree - Element at the root of the hierarchy (typically <registry>)
        apiName - the API name to process (e.g., 'vulkan', 'vulkansc')
    """
    ...

def stripNonmatchingAPIs(tree, apiName, actuallyDelete=...) -> None:
    """Remove tree Elements with 'api' attributes matching apiName.

        tree - Element at the root of the hierarchy to strip. Only its
            children can actually be removed, not the tree itself.
        apiName - string which much match a command-separated component of
            the 'api' attribute.
        actuallyDelete - only delete matching elements if True."""
    ...

class BaseInfo:
    """Base class for information about a registry feature
    (type/group/enum/command/API/extension).

    Represents the state of a registry feature, used during API generation.
    """
    def __init__(self, elem) -> None:
        ...
    
    def resetState(self) -> None:
        """Reset required/declared to initial values. Used
        prior to generating a new API interface."""
        ...
    
    def compareKeys(self, info, key, required=...) -> Literal[False]:
        """Return True if self.elem and info.elem have the same attribute
           value for key.
           If 'required' is not True, also returns True if neither element
           has an attribute value for key."""
        ...
    
    def compareElem(self, info, infoName) -> bool:
        """Return True if self.elem and info.elem have the same definition.
        info - the other object
        infoName - 'type' / 'group' / 'enum' / 'command' / 'feature' /
                   'extension'"""
        ...
    


class TypeInfo(BaseInfo):
    """Registry information about a type. No additional state
      beyond BaseInfo is required."""
    def __init__(self, elem) -> None:
        ...
    
    def getMembers(self):
        """Get a collection of all member elements for this type, if any."""
        ...
    
    def resetState(self) -> None:
        ...
    


class GroupInfo(BaseInfo):
    """Registry information about a group of related enums
    in an <enums> block, generally corresponding to a C "enum" type."""
    def __init__(self, elem) -> None:
        ...
    


class EnumInfo(BaseInfo):
    """Registry information about an enum"""
    def __init__(self, elem) -> None:
        ...
    


class CmdInfo(BaseInfo):
    """Registry information about a command"""
    def __init__(self, elem) -> None:
        ...
    
    def getParams(self):
        """Get a collection of all param elements for this command, if any."""
        ...
    
    def resetState(self) -> None:
        ...
    


class FeatureInfo(BaseInfo):
    """Registry information about an API <feature>
    or <extension>."""
    def __init__(self, elem) -> None:
        ...
    


class SpirvInfo(BaseInfo):
    """Registry information about an API <spirvextensions>
    or <spirvcapability>."""
    def __init__(self, elem) -> None:
        ...
    


class FormatInfo(BaseInfo):
    """Registry information about an API <format>."""
    def __init__(self, elem, condition) -> None:
        ...
    


class SyncStageInfo(BaseInfo):
    """Registry information about <syncstage>."""
    def __init__(self, elem, condition) -> None:
        ...
    


class SyncAccessInfo(BaseInfo):
    """Registry information about <syncaccess>."""
    def __init__(self, elem, condition) -> None:
        ...
    


class SyncPipelineInfo(BaseInfo):
    """Registry information about <syncpipeline>."""
    def __init__(self, elem) -> None:
        ...
    


class Registry:
    """Object representing an API registry, loaded from an XML file."""
    def __init__(self, gen=..., genOpts=...) -> None:
        ...
    
    def loadElementTree(self, tree) -> None:
        """Load ElementTree into a Registry object and parse it."""
        ...
    
    def loadFile(self, file) -> None:
        """Load an API registry XML file into a Registry object and parse it"""
        ...
    
    def setGenerator(self, gen) -> None:
        """Specify output generator object.

        `None` restores the default generator."""
        ...
    
    def addElementInfo(self, elem, info, infoName, dictionary) -> None:
        """Add information about an element to the corresponding dictionary.

        Intended for internal use only.

        - elem - `<type>`/`<enums>`/`<enum>`/`<command>`/`<feature>`/`<extension>`/`<spirvextension>`/`<spirvcapability>`/`<format>`/`<syncstage>`/`<syncaccess>`/`<syncpipeline>` Element
        - info - corresponding {Type|Group|Enum|Cmd|Feature|Spirv|Format|SyncStage|SyncAccess|SyncPipeline}Info object
        - infoName - 'type' / 'group' / 'enum' / 'command' / 'feature' / 'extension' / 'spirvextension' / 'spirvcapability' / 'format' / 'syncstage' / 'syncaccess' / 'syncpipeline'
        - dictionary - self.{type|group|enum|cmd|api|ext|format|spirvext|spirvcap|sync}dict

        The dictionary key is the element 'name' attribute."""
        ...
    
    def lookupElementInfo(self, fname, dictionary) -> None:
        """Find a {Type|Enum|Cmd}Info object by name.

        Intended for internal use only.

        If an object qualified by API name exists, use that.

        - fname - name of type / enum / command
        - dictionary - self.{type|enum|cmd}dict"""
        ...
    
    def breakOnName(self, regexp) -> None:
        """Specify a feature name regexp to break on when generating features."""
        ...
    
    def addEnumValue(self, enum, type_name) -> None:
        """Track aliasing and map back from enum values to their type"""
        ...
    
    def parseTree(self) -> None:
        """Parse the registry Element, once created"""
        ...
    
    def dumpReg(self, maxlen=..., filehandle=...) -> None:
        """Dump all the dictionaries constructed from the Registry object.

        Diagnostic to dump the dictionaries to specified file handle (default stdout).
        Truncates type / enum / command elements to maxlen characters (default 120)"""
        ...
    
    def markTypeRequired(self, typename, required) -> None:
        """Require (along with its dependencies) or remove (but not its dependencies) a type.

        - typename - name of type
        - required - boolean (to tag features as required or not)
        """
        ...
    
    def markEnumRequired(self, enumname, required) -> None:
        """Mark an enum as required or not.

        - enumname - name of enum
        - required - boolean (to tag features as required or not)"""
        ...
    
    def markCmdRequired(self, cmdname, required) -> None:
        """Mark a command as required or not.

        - cmdname - name of command
        - required - boolean (to tag features as required or not)"""
        ...
    
    def markRequired(self, featurename, feature, required) -> None:
        """Require or remove features specified in the Element.

        - featurename - name of the feature
        - feature - Element for `<require>` or `<remove>` tag
        - required - boolean (to tag features as required or not)"""
        ...
    
    def getAlias(self, elem, dict):
        """Check for an alias in the same require block.

        - elem - Element to check for an alias"""
        ...
    
    def checkForCorrectionAliases(self, alias, require, tag) -> Literal[False]:
        """Check for an alias in the same require block.

        - alias - String name of the alias
        - require -  `<require>` block from the registry
        - tag - tag to look for in the require block"""
        ...
    
    def requireDependsSatisfied(self, require) -> bool:
        """Return True if the require element has no depends attribute, or if the
        depends boolean expression evaluates to true.
        Used to exclude require block contents when building APIs (e.g. VulkanSC)
        that do not enable the depended-on features."""
        ...
    
    def fillFeatureDictionary(self, interface, featurename, api, profile) -> None:
        """Capture added interfaces for a `<version>` or `<extension>`.

        - interface - Element for `<version>` or `<extension>`, containing
          `<require>` and `<remove>` tags
        - featurename - name of the feature
        - api - string specifying API name being generated
        - profile - string specifying API profile being generated"""
        ...
    
    def requireFeatures(self, interface, featurename, api, profile) -> None:
        """Process `<require>` tags for a `<version>` or `<extension>`.

        - interface - Element for `<version>` or `<extension>`, containing
          `<require>` tags
        - featurename - name of the feature
        - api - string specifying API name being generated
        - profile - string specifying API profile being generated"""
        ...
    
    def deprecateFeatures(self, interface, featurename, api, profile) -> None:
        """Process `<require>` tags for a `<version>` or `<extension>`.

        - interface - Element for `<version>` or `<extension>`, containing
          `<require>` tags
        - featurename - name of the feature
        - api - string specifying API name being generated
        - profile - string specifying API profile being generated"""
        ...
    
    def removeFeatures(self, interface, featurename, api, profile) -> None:
        """Process `<remove>` tags for a `<version>` or `<extension>`.

        - interface - Element for `<version>` or `<extension>`, containing
          `<remove>` tags
        - featurename - name of the feature
        - api - string specifying API name being generated
        - profile - string specifying API profile being generated"""
        ...
    
    def assignAdditionalValidity(self, interface, api, profile) -> None:
        ...
    
    def removeAdditionalValidity(self, interface, api, profile) -> None:
        ...
    
    def generateFeature(self, fname, ftype, dictionary, explicit=...):
        """Generate a single type / enum group / enum / command,
        and all its dependencies as needed.

        - fname - name of feature (`<type>`/`<enum>`/`<command>`)
        - ftype - type of feature, 'type' | 'enum' | 'command'
        - dictionary - of *Info objects - self.{type|enum|cmd}dict
        - explicit - True if this is explicitly required by the top-level
          XML <require> tag, False if it is a dependency of an explicit
          requirement."""
        ...
    
    def generateRequiredInterface(self, interface) -> None:
        """Generate all interfaces required by an API version or extension.

        - interface - Element for `<version>` or `<extension>`"""
        ...
    
    def generateSpirv(self, spirv, dictionary) -> None:
        ...
    
    def stripUnsupportedAPIs(self, dictionary, attribute, supportedDictionary) -> None:
        """Strip unsupported APIs from attributes of APIs.
           dictionary - *Info dictionary of APIs to be updated
           attribute - attribute name to look for in each API
           supportedDictionary - dictionary in which to look for supported
            API elements in the attribute"""
        ...
    
    def stripUnsupportedAPIsFromList(self, dictionary, supportedDictionary) -> None:
        """Strip unsupported APIs from attributes of APIs.
           dictionary - dictionary of list of structure name strings
           supportedDictionary - dictionary in which to look for supported
            API elements in the attribute"""
        ...
    
    def generateFormat(self, format, dictionary) -> None:
        ...
    
    def generateSyncStage(self, sync) -> None:
        ...
    
    def generateSyncAccess(self, sync) -> None:
        ...
    
    def generateSyncPipeline(self, sync) -> None:
        ...
    
    def tagValidExtensionStructs(self) -> None:
        """Construct a "validextensionstructs" list for parent structures
           based on "structextends" tags in child structures.
           Only do this for structures tagged as required."""
        ...
    
    def apiGen(self) -> None:
        """Generate interface for specified versions using the current
        generator and generator options"""
        ...
    
    def apiReset(self) -> None:
        """Reset type/enum/command dictionaries before generating another API.

        Use between apiGen() calls to reset internal state."""
        ...
    


