"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass, field
from enum import Enum

@dataclass
class FeatureRequirement:
    """Each instance of FeatureRequirement is one part of the AND operation,
       unless the struct/field are the same, then the depends are AND togethered"""
    struct: str
    field: str
    depends: (str | None)
    ...


@dataclass
class Extension:
    """<extension>"""
    name: str
    nameString: str
    specVersion: str
    specVersionValue: int
    instance: bool
    device: bool
    depends: (str | None)
    vendorTag: (str | None)
    platform: (str | None)
    protect: (str | None)
    provisional: bool
    promotedTo: (str | None)
    deprecatedBy: (str | None)
    obsoletedBy: (str | None)
    specialUse: list[str]
    featureRequirement: list[FeatureRequirement]
    ratified: bool
    handles: list[Handle] = ...
    commands: list[Command] = ...
    structs: list[Struct] = ...
    enums: list[Enum] = ...
    bitmasks: list[Bitmask] = ...
    flags: list[Flags] = ...
    enumFields: dict[str, list[EnumField]] = ...
    flagBits: dict[str, list[Flag]] = ...


@dataclass
class Version:
    """
    <feature> which represents a version
    This will NEVER be Version 1.0, since having 'no version' is same as being 1.0
    """
    name: str
    nameString: str
    nameApi: str
    featureRequirement: list[FeatureRequirement]
    ...


@dataclass
class Legacy:
    """<deprecate>
    For historical reasons, the XML tag is "deprecate" but we decided in the WG to not use that as the public facing name
    """
    link: (str | None)
    version: (Version | None)
    extensions: list[str]
    supersededBy: (str | None)
    ...


@dataclass
class Handle:
    """<type> which represents a dispatch handle"""
    name: str
    aliases: list[str]
    type: str
    protect: (str | None)
    parent: (Handle | None)
    instance: bool
    device: bool
    dispatchable: bool
    extensions: list[str]
    definingRequirements: dict[str, str | None] = ...
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class FuncPointerParam:
    """<funcpointer/param>"""
    name: str
    type: str
    fullType: str
    cDeclaration: str
    ...


@dataclass
class FuncPointer:
    """<funcpointer>"""
    name: str
    protect: (str | None)
    returnType: str
    requires: (str | None)
    params: list[FuncPointerParam]
    cFunctionPointer: str
    ...


class ExternSync(Enum):
    NONE = ...
    ALWAYS = ...
    MAYBE = ...
    SUBTYPE = ...
    SUBTYPE_MAYBE = ...


@dataclass
class Param:
    """<command/param>"""
    name: str
    alias: (str | None)
    type: str
    fullType: str
    noAutoValidity: bool
    const: bool
    length: (str | None)
    nullTerminated: bool
    pointer: bool
    fixedSizeArray: list[str]
    optional: bool
    optionalPointer: bool
    externSync: ExternSync
    externSyncPointer: (str | None)
    cDeclaration: str
    def __lt__(self, other) -> bool:
        ...
    


class CommandScope(Enum):
    NONE = ...
    INSIDE = ...
    OUTSIDE = ...
    BOTH = ...


@dataclass
class Command:
    """<command>"""
    name: str
    alias: (str | None)
    protect: (str | None)
    extensions: list[str]
    version: (Version | None)
    returnType: str
    params: list[Param]
    instance: bool
    device: bool
    tasks: list[str]
    queues: list[str]
    allowNoQueues: bool
    successCodes: list[str]
    errorCodes: list[str]
    primary: bool
    secondary: bool
    renderPass: CommandScope
    videoCoding: CommandScope
    implicitExternSyncParams: list[str]
    legacy: (Legacy | None)
    cPrototype: str
    cFunctionPointer: str
    definingRequirements: dict[str, str | None] = ...
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class ExtendedFlag:
    struct: str
    ...


@dataclass
class StructCapabilityAlias:
    """An alias that points to a member inside another feature structure."""
    struct: str
    member: str
    ...


@dataclass
class ExtensionCapabilityAlias:
    """An alias indicating the feature is enabled using the extension."""
    name: str
    ...


CapabilityAlias = StructCapabilityAlias | ExtensionCapabilityAlias
@dataclass
class Member:
    """<member>"""
    name: str
    capabilityAlias: (CapabilityAlias | None)
    type: str
    fullType: str
    noAutoValidity: bool
    limitType: (str | None)
    const: bool
    length: (str | None)
    nullTerminated: bool
    pointer: bool
    fixedSizeArray: list[str]
    extendedFlag: (ExtendedFlag | None)
    optional: bool
    optionalPointer: bool
    externSync: ExternSync
    cDeclaration: str
    bitFieldWidth: (int | None)
    selector: (str | None)
    selection: list[str]
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class Struct:
    """<type category="struct"> or <type category="union">"""
    name: str
    aliases: list[str]
    extensions: list[str]
    version: (Version | None)
    protect: (str | None)
    members: list[Member]
    union: bool
    returnedOnly: bool
    sType: (str | None)
    allowDuplicate: bool
    extends: list[str]
    extendedBy: list[str]
    definingRequirements: dict[str, str | None] = ...
    videoStdHeader: (str | None) = ...
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class EnumField:
    """<enum> of type enum"""
    name: str
    aliases: list[str]
    parent: str
    protect: (str | None)
    negative: bool
    value: int
    valueStr: str
    extensions: list[str]
    extending: bool
    definingRequirements: dict[str, str | None] = ...
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class Enum:
    """<enums> of type enum"""
    name: str
    aliases: list[str]
    protect: (str | None)
    bitWidth: int
    returnedOnly: bool
    fields: list[EnumField]
    extensions: list[str]
    fieldExtensions: list[str]
    definingRequirements: dict[str, str | None] = ...
    videoStdHeader: (str | None) = ...
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class Flag:
    """<enum> of type bitmask"""
    name: str
    aliases: list[str]
    parent: str
    protect: (str | None)
    value: int
    valueStr: str
    bitpos: (int | None)
    multiBit: bool
    zero: bool
    extensions: list[str]
    extending: bool
    definingRequirements: dict[str, str | None] = ...
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class Bitmask:
    """<enums> of type bitmask"""
    name: str
    aliases: list[str]
    flagName: str
    protect: (str | None)
    bitWidth: int
    returnedOnly: bool
    flags: list[Flag]
    extensions: list[str]
    flagExtensions: list[str]
    definingRequirements: dict[str, str | None] = ...
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class Flags:
    """<type> defining flags types"""
    name: str
    aliases: list[str]
    bitmaskName: (str | None)
    protect: (str | None)
    baseFlagsType: str
    bitWidth: int
    returnedOnly: bool
    extensions: list[str]
    definingRequirements: dict[str, str | None] = ...
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class Constant:
    name: str
    type: str
    value: (int | float)
    valueStr: str
    videoStdHeader: (str | None) = ...


@dataclass
class FormatComponent:
    """<format/component>"""
    type: str
    bits: str
    numericFormat: str
    planeIndex: (int | None)
    ...


@dataclass
class FormatPlane:
    """<format/plane>"""
    index: int
    widthDivisor: int
    heightDivisor: int
    compatible: str
    ...


@dataclass
class Format:
    """<format>"""
    name: str
    className: str
    blockSize: int
    texelsPerBlock: int
    blockExtent: list[str]
    packed: (int | None)
    chroma: (str | None)
    compressed: (str | None)
    components: list[FormatComponent]
    planes: list[FormatPlane]
    spirvImageFormat: (str | None)
    ...


@dataclass
class SyncSupport:
    """<syncsupport>"""
    queues: (list[str] | None)
    stages: (list[Flag] | None)
    max: bool
    ...


@dataclass
class SyncEquivalent:
    """<syncequivalent>"""
    stages: (list[Flag] | None)
    accesses: (list[Flag] | None)
    max: bool
    ...


@dataclass
class SyncStage:
    """<syncstage>"""
    flag: Flag
    support: SyncSupport
    equivalent: SyncEquivalent
    ...


@dataclass
class SyncAccess:
    """<syncaccess>"""
    flag: Flag
    support: SyncSupport
    equivalent: SyncEquivalent
    ...


@dataclass
class SyncPipelineStage:
    """<syncpipelinestage>"""
    order: (str | None)
    before: (str | None)
    after: (str | None)
    value: str
    ...


@dataclass
class SyncPipeline:
    """<syncpipeline>"""
    name: str
    depends: list[str]
    stages: list[SyncPipelineStage]
    ...


@dataclass
class SpirvEnables:
    """What is needed to enable the SPIR-V element"""
    version: (str | None)
    extension: (str | None)
    struct: (str | None)
    feature: (str | None)
    requires: (str | None)
    property: (str | None)
    member: (str | None)
    value: (str | None)
    ...


@dataclass
class Spirv:
    """<spirvextension> and <spirvcapability>"""
    name: str
    extension: bool
    capability: bool
    enable: list[SpirvEnables]
    ...


@dataclass
class VideoRequiredCapabilities:
    """<videorequirecapabilities>"""
    struct: str
    member: str
    value: str
    ...


@dataclass
class VideoFormat:
    """<videoformat>"""
    name: str
    usage: str
    requiredCaps: list[VideoRequiredCapabilities]
    properties: dict[str, str]
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class VideoProfileMember:
    """<videoprofilemember> and <videoprofile>"""
    name: str
    values: dict[str, str]
    ...


@dataclass
class VideoProfiles:
    """<videoprofiles>"""
    name: str
    members: dict[str, VideoProfileMember]
    ...


@dataclass
class VideoCodec:
    """<videocodec>"""
    name: str
    value: (str | None)
    profiles: dict[str, VideoProfiles]
    capabilities: dict[str, str]
    formats: dict[str, VideoFormat]
    def __lt__(self, other) -> bool:
        ...
    


@dataclass
class VideoStdHeader:
    """<extension> in video.xml"""
    name: str
    version: (str | None)
    headerFile: str
    depends: list[str]
    ...


@dataclass
class VideoStd:
    headers: dict[str, VideoStdHeader] = ...
    enums: dict[str, Enum] = ...
    structs: dict[str, Struct] = ...
    constants: dict[str, Constant] = ...


@dataclass
class VulkanObject:
    headerVersion: str = ...
    headerVersionComplete: str = ...
    extensions: dict[str, Extension] = ...
    versions: dict[str, Version] = ...
    handles: dict[str, Handle] = ...
    commands: dict[str, Command] = ...
    structs: dict[str, Struct] = ...
    enums: dict[str, Enum] = ...
    bitmasks: dict[str, Bitmask] = ...
    flags: dict[str, Flags] = ...
    constants: dict[str, Constant] = ...
    formats: dict[str, Format] = ...
    funcPointers: dict[str, FuncPointer] = ...
    syncStage: list[SyncStage] = ...
    syncAccess: list[SyncAccess] = ...
    syncPipeline: list[SyncPipeline] = ...
    spirv: list[Spirv] = ...
    platforms: dict[str, str] = ...
    vendorTags: list[str] = ...
    aliasTypeRequirements: dict[str, dict[str, str | None]] = ...
    aliasFieldRequirements: dict[str, dict[str, str | None]] = ...
    aliasFlagRequirements: dict[str, dict[str, str | None]] = ...
    videoCodecs: dict[str, VideoCodec] = ...
    videoStd: (VideoStd | None) = ...


