"""
This type stub file was generated by pyright.
"""

import abc
from enum import Enum

CATEGORIES_REQUIRING_VALIDATION = ...
TYPES_KNOWN_ALWAYS_VALID = ...
EXT_NAME_DECOMPOSE_RE = ...
API_VERSION_NAME_RE = ...
class ProseListFormats(Enum):
    """A connective, possibly with a quantifier."""
    AND = ...
    EACH_AND = ...
    OR = ...
    ANY_OR = ...
    @classmethod
    def from_string(cls, s) -> Literal[ProseListFormats.OR, ProseListFormats.AND]:
        ...
    
    @property
    def connective(self) -> Literal['or', 'and']:
        ...
    
    def quantifier(self, n) -> Literal['any of ', 'each of ', 'both of ', '']:
        """Return the desired quantifier for a list of a given length."""
        ...
    


class ConventionsBase(abc.ABC):
    """WG-specific conventions."""
    def __init__(self) -> None:
        ...
    
    def formatVersionOrExtension(self, name) -> str:
        """Mark up an API version or extension name as a link in the spec."""
        ...
    
    def formatVersion(self, name, apivariant, major, minor) -> str:
        """Mark up an API version name as a link in the spec."""
        ...
    
    def formatExtension(self, name) -> str:
        """Mark up an extension name as a link in the spec."""
        ...
    
    def formatSPIRVlink(self, name) -> str:
        """Mark up a SPIR-V extension name as an external link in the spec.
           Since these are external links, the formatting probably will be
           the same for all APIs creating such links, so long as they use
           the asciidoctor {spirv} attribute for the base path to the SPIR-V
           extensions."""
        ...
    
    @property
    @abc.abstractmethod
    def null(self):
        """Preferred spelling of NULL."""
        ...
    
    def makeProseList(self, elements, fmt=..., with_verb=..., *args, **kwargs) -> str:
        """Make a (comma-separated) list for use in prose.

        Adds a connective (by default, 'and')
        before the last element if there are more than 1.

        Adds the right one of "is" or "are" to the end if with_verb is true.

        Optionally adds a quantifier (like 'any') before a list of 2 or more,
        if specified by fmt.

        Override with a different method or different call to
        _implMakeProseList if you want to add a comma for two elements,
        or not use a serial comma.
        """
        ...
    
    @property
    def struct_macro(self) -> Literal['slink:']:
        """Get the appropriate format macro for a structure.

        May override.
        """
        ...
    
    @property
    def external_macro(self) -> Literal['code:']:
        """Get the appropriate format macro for an external type like uint32_t.

        May override.
        """
        ...
    
    @property
    def allows_x_number_suffix(self) -> Literal[False]:
        """Whether vendor tags can be suffixed with X and a number to mark experimental extensions."""
        ...
    
    @property
    @abc.abstractmethod
    def structtype_member_name(self):
        """Return name of the structure type member.

        Must implement.
        """
        ...
    
    @property
    @abc.abstractmethod
    def nextpointer_member_name(self):
        """Return name of the structure pointer chain member.

        Must implement.
        """
        ...
    
    @property
    @abc.abstractmethod
    def xml_api_name(self):
        """Return the name used in the default API XML registry for the default API"""
        ...
    
    @abc.abstractmethod
    def generate_structure_type_from_name(self, structname):
        """Generate a structure type name, like XR_TYPE_CREATE_INSTANCE_INFO.

        Must implement.
        """
        ...
    
    def makeStructName(self, name):
        """Prepend the appropriate format macro for a structure to a structure type name.

        Uses struct_macro, so just override that if you want to change behavior.
        """
        ...
    
    def makeExternalTypeName(self, name):
        """Prepend the appropriate format macro for an external type like uint32_t to a type name.

        Uses external_macro, so just override that if you want to change behavior.
        """
        ...
    
    @property
    @abc.abstractmethod
    def file_suffix(self):
        """Return suffix of generated Asciidoctor files"""
        ...
    
    @abc.abstractmethod
    def api_name(self, spectype=...):
        """Return API or specification name for citations in ref pages.

        spectype is the spec this refpage is for.
        'api' (the default value) is the main API Specification.
        If an unrecognized spectype is given, returns None.

        Must implement."""
        ...
    
    def should_insert_may_alias_macro(self, genOpts) -> Literal[False]:
        """Return true if we should insert a "may alias" macro in this file.

        Only used by OpenXR right now."""
        ...
    
    @property
    def command_prefix(self):
        """Return the expected prefix of commands/functions.

        Implemented in terms of api_prefix."""
        ...
    
    @property
    def type_prefix(self) -> LiteralString | str:
        """Return the expected prefix of type names.

        Implemented in terms of command_prefix (and in turn, api_prefix)."""
        ...
    
    @property
    @abc.abstractmethod
    def api_prefix(self):
        """Return API token prefix.

        Typically two uppercase letters followed by an underscore.

        Must implement."""
        ...
    
    @property
    def extension_name_prefix(self):
        """Return extension name prefix.

        Typically two uppercase letters followed by an underscore.

        Assumed to be the same as api_prefix, but some APIs use different
        case conventions."""
        ...
    
    def extension_short_description(self, elem) -> str:
        """Return a short description of an extension for use in refpages.

        elem is an ElementTree for the <extension> tag in the XML.
        The default behavior is to use the 'type' field of this tag, but not
        all APIs support this field."""
        ...
    
    @property
    def write_contacts(self) -> Literal[False]:
        """Return whether contact list should be written to extension appendices"""
        ...
    
    @property
    def write_extension_type(self) -> Literal[True]:
        """Return whether extension type should be written to extension appendices"""
        ...
    
    @property
    def write_extension_number(self) -> Literal[True]:
        """Return whether extension number should be written to extension appendices"""
        ...
    
    @property
    def write_extension_revision(self) -> Literal[True]:
        """Return whether extension revision number should be written to extension appendices"""
        ...
    
    @property
    def write_refpage_include(self) -> Literal[True]:
        """Return whether refpage include should be written to extension appendices"""
        ...
    
    @property
    def api_version_prefix(self) -> str:
        """Return API core version token prefix.

        Implemented in terms of api_prefix.

        May override."""
        ...
    
    @property
    def KHR_prefix(self) -> str:
        """Return extension name prefix for KHR extensions.

        Implemented in terms of api_prefix.

        May override."""
        ...
    
    @property
    def EXT_prefix(self) -> str:
        """Return extension name prefix for EXT extensions.

        Implemented in terms of api_prefix.

        May override."""
        ...
    
    def writeFeature(self, featureName, featureExtraProtect, filename) -> Literal[True]:
        """Return True if OutputGenerator.endFeature should write this feature.

        Defaults to always True.
        Used in COutputGenerator.

        May override."""
        ...
    
    def requires_error_validation(self, return_type) -> Literal[False]:
        """Return True if the return_type element is an API result code
        requiring error validation.

        Defaults to always False.

        May override."""
        ...
    
    @property
    def required_errors(self) -> list[Any]:
        """Return a list of required error codes for validation.

        Defaults to an empty list.

        May override."""
        ...
    
    def is_voidpointer_alias(self, tag, text, tail):
        """Return True if the declaration components (tag,text,tail) of an
        element represents a void * type.

        Defaults to a reasonable implementation.

        May override."""
        ...
    
    def make_voidpointer_alias(self, tail):
        """Reformat a void * declaration to include the API alias macro.

        Defaults to a no-op.

        Must override if you actually want to use this feature in your project."""
        ...
    
    def category_requires_validation(self, category) -> bool:
        """Return True if the given type 'category' always requires validation.

        Defaults to a reasonable implementation.

        May override."""
        ...
    
    def type_always_valid(self, typename) -> bool:
        """Return True if the given type name is always valid (never requires validation).

        This is for things like integers.

        Defaults to a reasonable implementation.

        May override."""
        ...
    
    @property
    def should_skip_checking_codes(self) -> Literal[False]:
        """Return True if more than the basic validation of return codes should
        be skipped for a command."""
        ...
    
    @property
    def generate_index_terms(self) -> Literal[False]:
        """Return True if asiidoctor index terms should be generated as part
           of an API interface from the docgenerator."""
        ...
    
    @property
    def generate_enum_table(self) -> Literal[False]:
        """Return True if asciidoctor tables describing enumerants in a
           group should be generated as part of group generation."""
        ...
    
    @property
    def generate_max_enum_in_docs(self) -> Literal[False]:
        """Return True if MAX_ENUM tokens should be generated in
           documentation includes."""
        ...
    
    def extension_name_split(self, name) -> tuple[str | Any, str | Any]:
        """Split an extension name, returning (vendor, rest of name).
           The API prefix of the name is ignored."""
        ...
    
    @abc.abstractmethod
    def extension_file_path(self, name):
        """Return file path to an extension appendix relative to a directory
           containing all such appendices.
           - name - extension name

           Must implement."""
        ...
    
    def extension_include_string(self, name) -> str:
        """Return format string for include:: line for an extension appendix
           file.
            - name - extension name"""
        ...
    
    @property
    def provisional_extension_warning(self) -> Literal[True]:
        """Return True if a warning should be included in extension
           appendices for provisional extensions."""
        ...
    
    @property
    def generated_include_path(self) -> Literal['{generated}']:
        """Return path relative to the generated reference pages, to the
           generated API include files."""
        ...
    
    @property
    def include_extension_appendix_in_refpage(self) -> Literal[True]:
        """Return True if generating extension refpages by embedding
           extension appendix content (default), False otherwise
           (OpenXR)."""
        ...
    
    def valid_flag_bit(self, bitpos) -> Literal[True]:
        """Return True if bitpos is an allowed numeric bit position for
           an API flag.

           Behavior depends on the data type used for flags (which may be 32
           or 64 bits), and may depend on assumptions about compiler
           handling of sign bits in enumerated types, as well."""
        ...
    
    @property
    def duplicate_aliased_structs(self) -> Literal[False]:
        """
        Should aliased structs have the original struct definition listed in the
        generated docs snippet?
        """
        ...
    
    @property
    def protectProtoComment(self) -> Literal[False]:
        """Return True if generated #endif should have a comment matching
           the protection symbol used in the opening #ifdef/#ifndef."""
        ...
    
    @property
    def extra_refpage_headers(self) -> Literal['']:
        """Return any extra headers (preceding the title) for generated
           reference pages."""
        ...
    
    @property
    def extra_refpage_body(self) -> Literal['']:
        """Return any extra text (following the title) for generated
           reference pages."""
        ...
    
    def is_api_version_name(self, name) -> bool:
        """Return True if name is an API version name."""
        ...
    
    @property
    def docgen_language(self) -> Literal['c']:
        """Return the language to be used in docgenerator [source]
           blocks."""
        ...
    
    @property
    def docgen_source_options(self) -> Literal['%unbreakable']:
        """Return block options to be used in docgenerator [source] blocks,
           which are appended to the 'source' block type.
           Can be empty."""
        ...
    


