"""
This type stub file was generated by pyright.
"""

"""Utility functions not closely tied to other spec_tools types."""
def getElemName(elem, default=...):
    """Get the name associated with an element, either a name child or name attribute."""
    ...

def getElemType(elem, default=...):
    """Get the type associated with an element, either a type child or type attribute."""
    ...

def findFirstWithPredicate(collection, pred) -> None:
    """Return the first element that satisfies the predicate, or None if none exist.

    NOTE: Some places where this is used might be better served by changing to a dictionary.
    """
    ...

def findNamedElem(elems, name) -> None:
    """Traverse a collection of elements with 'name' nodes or attributes, looking for and returning one with the right name.

    NOTE: Many places where this is used might be better served by changing to a dictionary.
    """
    ...

def findTypedElem(elems, typename) -> None:
    """Traverse a collection of elements with 'type' nodes or attributes, looking for and returning one with the right typename.

    NOTE: Many places where this is used might be better served by changing to a dictionary.
    """
    ...

def findNamedObject(collection, name) -> None:
    """Traverse a collection of elements with 'name' attributes, looking for and returning one with the right name.

    NOTE: Many places where this is used might be better served by changing to a dictionary.
    """
    ...

