[package]
name = "vkx"
version = "0.1.0+1.4.362"
edition = "2024"

[dependencies]
libloading = "0.9.0"
raw-window-handle = { version = "0.6.2", features = ["std"], optional = true }
thiserror = { version = "2.0.20", optional = true }
zerocopy = "0.8.57"

[dev-dependencies]
shaderc = "0.10"
winit = "0.30.13"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
raw-window-metal = { version = "1.1.0", features = ["std"], optional = true }

[features]
default = ["window"]
window = ["dep:raw-window-handle", "dep:raw-window-metal", "dep:thiserror"]
